host: 192.168.0.157
port: 8083
title: Baichao
email: qbaichao@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
author :
  name : Baichao
  logo: /assets/images/github_logo.jpg
  motto: 脚踏实地，仰望星空，专心练剑
  wechat: /assets/images/wechat.jpg
  url: /about.html
  email : qbaichao@gmail.com
  github : https://github.com/qinbaichao
markdown: kramdown
permalink: /:year/:month/:day/:title:output_ext
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
